CREATE EXTENSION IF NOT EXISTS postgis;

create table movies
(
    release_date  date,
    created_at    timestamp(6),
    genre         varchar(20),
    external_code varchar(50),
    image         varchar(512),
    director      varchar(255),
    id            varchar(255) not null
        primary key,
    title         varchar(255) not null
        constraint movies_title_unique
            unique
);


create table events
(
    view_count integer,
    created_at timestamp(6),
    end_at     timestamp(6) not null,
    start_at   timestamp(6) not null,
    type       varchar(20)
        constraint events_type_check
            check ((type)::text = ANY
        ((ARRAY ['GOODS'::character varying, 'COUPON'::character varying, 'GV'::character varying])::text[])),
    id         varchar(255) not null
        primary key
        constraint unique_event_id
            unique
        constraint events_id_unique
            unique,
    movie_id   varchar(255) not null
        constraint fk4j208mivjj6bidknfip65be50
            references movies,
    title      varchar(255) not null
);


create table theaters
(
    brand    varchar(20)           not null,
    name     varchar(50)           not null,
    address  varchar(255)          not null,
    id       varchar(255)          not null
        primary key,
    location geometry(Point, 4326) not null
);


create table event_location
(
    updated_at timestamp(6) not null,
    status     varchar(50)  not null,
    event_id   varchar(255) not null
        constraint fkopb5q5s8ospjlobrvqt4cxgdw
            references events,
    id         varchar(255) not null
        primary key,
    theater_id varchar(255) not null
        constraint fkawt6xe4yj285fo8amw2d4q41j
            references theaters,
    constraint event_location_unique
        unique (theater_id, event_id)
);


create table members
(
    created_at timestamp(6) not null,
    id         bigint       not null
        constraint users_pkey
            primary key,
    role       varchar(255) not null
        constraint users_role_check
            check ((role)::text = ANY (ARRAY [('USER'::character varying)::text, ('ADMIN'::character varying)::text])),
    email      varchar(255) not null,
    fcm_token  varchar(255),
    nickname   varchar(255) not null,
    password   varchar(255) not null
);


create table theater_subscription
(
    created_at timestamp(6) not null,
    user_id    bigint       not null
        constraint fkqh6wv5hn3wnra2i540vtsfa9w
            references members,
    id         varchar(255) not null
        primary key,
    theater_id varchar(255) not null
        constraint fktmakdmoqnnpbyf8pwh5egb7qi
            references theaters
);


create table users
(
    id         bigint generated by default as identity
        constraint users_pkey1
            primary key,
    created_at timestamp(6),
    email      varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    fcm_token  varchar(255),
    location   geometry(Point, 4326),
    nickname   varchar(255) not null,
    password   varchar(255) not null,
    role       varchar(255) not null
);


